# /site.yml
---
- name: Main YML for k8s cluster configuration
  hosts: kubernetes
  become: yes
  vars_files:
    - ./group_vars/all.yml
  roles:
    - name: k8s configuration
      role: k8s_dependencies

- name: Confgiure cluster primary
  hosts: primary
  become: yes
  vars_files:
    - ./group_vars/all.yml
  roles:
    - name: Cluster primary
      role: k8s_primary

#- name: Confgiure cluster nodes
#  hosts: nodes
#  become: yes
#  vars_files:
#    - ./group_vars/all.yml
#  roles:
#    - name: Cluster node
#      role: k8s_node
...