# /roles/k8s/tasks/install_cluster_primary.yml
---
- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

# Configure k8s primary
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME/.kube
    creates: cluster_initialized.txt

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root

- name: install Pod network
  shell: kubectl apply -f "{{ pod_network }}" >> pod_network_setup.txt
  args:
    chdir: $HOME/.kube
    creates: pod_network_setup.txt

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
...