# /roles/k8s/tasks/install_cluster_node.yml
---
# Configure k8s node
- name: join cluster
  shell: "{{ hostvars['primary1'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
...